//
// AddPlaylist200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AddPlaylist200Response: Codable, JSONEncodable, Hashable {

    public var videoPlaylist: AddPlaylist200ResponseVideoPlaylist?

    public init(videoPlaylist: AddPlaylist200ResponseVideoPlaylist? = nil) {
        self.videoPlaylist = videoPlaylist
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case videoPlaylist
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(videoPlaylist, forKey: .videoPlaylist)
    }
}

