//
// ApiV1ServerFollowingPostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ApiV1ServerFollowingPostRequest: Codable, JSONEncodable, Hashable {

    public var hosts: Set<String>?
    public var handles: Set<String>?

    public init(hosts: Set<String>? = nil, handles: Set<String>? = nil) {
        self.hosts = hosts
        self.handles = handles
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case hosts
        case handles
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(hosts, forKey: .hosts)
        try container.encodeIfPresent(handles, forKey: .handles)
    }
}

