//
// ApiV1VideoChannelsChannelHandleBannerPickPost200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ApiV1VideoChannelsChannelHandleBannerPickPost200Response: Codable, JSONEncodable, Hashable {

    public var banners: [ActorImage]?

    public init(banners: [ActorImage]? = nil) {
        self.banners = banners
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case banners
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(banners, forKey: .banners)
    }
}

