//
// GetUser200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum GetUser200Response: Codable, JSONEncodable, Hashable {
    case typeUser(User)
    case typeUserWithStats(UserWithStats)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeUser(let value):
            try container.encode(value)
        case .typeUserWithStats(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(User.self) {
            self = .typeUser(value)
        } else if let value = try? container.decode(UserWithStats.self) {
            self = .typeUserWithStats(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of GetUser200Response"))
        }
    }
}

