//
// NotificationComment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct NotificationComment: Codable, JSONEncodable, Hashable {

    static let idRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var id: Int?
    public var threadId: Int?
    public var video: VideoInfo?
    public var account: ActorInfo?

    public init(id: Int? = nil, threadId: Int? = nil, video: VideoInfo? = nil, account: ActorInfo? = nil) {
        self.id = id
        self.threadId = threadId
        self.video = video
        self.account = account
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case threadId
        case video
        case account
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(threadId, forKey: .threadId)
        try container.encodeIfPresent(video, forKey: .video)
        try container.encodeIfPresent(account, forKey: .account)
    }
}

