//
// NotificationVideo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct NotificationVideo: Codable, JSONEncodable, Hashable {

    static let idRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var id: Int?
    public var uuid: Uuid?
    public var name: Name?
    public var channel: ActorInfo?

    public init(id: Int? = nil, uuid: Uuid? = nil, name: Name? = nil, channel: ActorInfo? = nil) {
        self.id = id
        self.uuid = uuid
        self.name = name
        self.channel = channel
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case uuid
        case name
        case channel
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(uuid, forKey: .uuid)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(channel, forKey: .channel)
    }
}

