//
// ServerConfigCustomInstance.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServerConfigCustomInstance: Codable, JSONEncodable, Hashable {

    public var name: String?
    public var shortDescription: String?
    public var description: String?
    public var terms: String?
    public var defaultClientRoute: String?
    public var isNSFW: Bool?
    public var defaultNSFWPolicy: String?
    public var customizations: ServerConfigInstanceCustomizations?

    public init(name: String? = nil, shortDescription: String? = nil, description: String? = nil, terms: String? = nil, defaultClientRoute: String? = nil, isNSFW: Bool? = nil, defaultNSFWPolicy: String? = nil, customizations: ServerConfigInstanceCustomizations? = nil) {
        self.name = name
        self.shortDescription = shortDescription
        self.description = description
        self.terms = terms
        self.defaultClientRoute = defaultClientRoute
        self.isNSFW = isNSFW
        self.defaultNSFWPolicy = defaultNSFWPolicy
        self.customizations = customizations
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case shortDescription
        case description
        case terms
        case defaultClientRoute
        case isNSFW
        case defaultNSFWPolicy
        case customizations
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(shortDescription, forKey: .shortDescription)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(terms, forKey: .terms)
        try container.encodeIfPresent(defaultClientRoute, forKey: .defaultClientRoute)
        try container.encodeIfPresent(isNSFW, forKey: .isNSFW)
        try container.encodeIfPresent(defaultNSFWPolicy, forKey: .defaultNSFWPolicy)
        try container.encodeIfPresent(customizations, forKey: .customizations)
    }
}

