//
// ServerConfigTrendingVideos.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServerConfigTrendingVideos: Codable, JSONEncodable, Hashable {

    public var intervalDays: Int?

    public init(intervalDays: Int? = nil) {
        self.intervalDays = intervalDays
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case intervalDays
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(intervalDays, forKey: .intervalDays)
    }
}

