//
// ServerConfigAutoBlacklist.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServerConfigAutoBlacklist: Codable, JSONEncodable, Hashable {

    public var videos: ServerConfigAutoBlacklistVideos?

    public init(videos: ServerConfigAutoBlacklistVideos? = nil) {
        self.videos = videos
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case videos
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(videos, forKey: .videos)
    }
}

