//
// ServerStats.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServerStats: Codable, JSONEncodable, Hashable {

    public var totalUsers: Double?
    public var totalDailyActiveUsers: Double?
    public var totalWeeklyActiveUsers: Double?
    public var totalMonthlyActiveUsers: Double?
    public var totalLocalVideos: Double?
    /** Total video views made on the instance */
    public var totalLocalVideoViews: Double?
    /** Total comments made by local users */
    public var totalLocalVideoComments: Double?
    public var totalLocalVideoFilesSize: Double?
    public var totalVideos: Double?
    public var totalVideoComments: Double?
    public var totalLocalVideoChannels: Double?
    public var totalLocalDailyActiveVideoChannels: Double?
    public var totalLocalWeeklyActiveVideoChannels: Double?
    public var totalLocalMonthlyActiveVideoChannels: Double?
    public var totalLocalPlaylists: Double?
    public var totalInstanceFollowers: Double?
    public var totalInstanceFollowing: Double?
    public var videosRedundancy: [ServerStatsVideosRedundancyInner]?
    public var totalActivityPubMessagesProcessed: Double?
    public var totalActivityPubMessagesSuccesses: Double?
    public var totalActivityPubMessagesErrors: Double?
    public var activityPubMessagesProcessedPerSecond: Double?
    public var totalActivityPubMessagesWaiting: Double?

    public init(totalUsers: Double? = nil, totalDailyActiveUsers: Double? = nil, totalWeeklyActiveUsers: Double? = nil, totalMonthlyActiveUsers: Double? = nil, totalLocalVideos: Double? = nil, totalLocalVideoViews: Double? = nil, totalLocalVideoComments: Double? = nil, totalLocalVideoFilesSize: Double? = nil, totalVideos: Double? = nil, totalVideoComments: Double? = nil, totalLocalVideoChannels: Double? = nil, totalLocalDailyActiveVideoChannels: Double? = nil, totalLocalWeeklyActiveVideoChannels: Double? = nil, totalLocalMonthlyActiveVideoChannels: Double? = nil, totalLocalPlaylists: Double? = nil, totalInstanceFollowers: Double? = nil, totalInstanceFollowing: Double? = nil, videosRedundancy: [ServerStatsVideosRedundancyInner]? = nil, totalActivityPubMessagesProcessed: Double? = nil, totalActivityPubMessagesSuccesses: Double? = nil, totalActivityPubMessagesErrors: Double? = nil, activityPubMessagesProcessedPerSecond: Double? = nil, totalActivityPubMessagesWaiting: Double? = nil) {
        self.totalUsers = totalUsers
        self.totalDailyActiveUsers = totalDailyActiveUsers
        self.totalWeeklyActiveUsers = totalWeeklyActiveUsers
        self.totalMonthlyActiveUsers = totalMonthlyActiveUsers
        self.totalLocalVideos = totalLocalVideos
        self.totalLocalVideoViews = totalLocalVideoViews
        self.totalLocalVideoComments = totalLocalVideoComments
        self.totalLocalVideoFilesSize = totalLocalVideoFilesSize
        self.totalVideos = totalVideos
        self.totalVideoComments = totalVideoComments
        self.totalLocalVideoChannels = totalLocalVideoChannels
        self.totalLocalDailyActiveVideoChannels = totalLocalDailyActiveVideoChannels
        self.totalLocalWeeklyActiveVideoChannels = totalLocalWeeklyActiveVideoChannels
        self.totalLocalMonthlyActiveVideoChannels = totalLocalMonthlyActiveVideoChannels
        self.totalLocalPlaylists = totalLocalPlaylists
        self.totalInstanceFollowers = totalInstanceFollowers
        self.totalInstanceFollowing = totalInstanceFollowing
        self.videosRedundancy = videosRedundancy
        self.totalActivityPubMessagesProcessed = totalActivityPubMessagesProcessed
        self.totalActivityPubMessagesSuccesses = totalActivityPubMessagesSuccesses
        self.totalActivityPubMessagesErrors = totalActivityPubMessagesErrors
        self.activityPubMessagesProcessedPerSecond = activityPubMessagesProcessedPerSecond
        self.totalActivityPubMessagesWaiting = totalActivityPubMessagesWaiting
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case totalUsers
        case totalDailyActiveUsers
        case totalWeeklyActiveUsers
        case totalMonthlyActiveUsers
        case totalLocalVideos
        case totalLocalVideoViews
        case totalLocalVideoComments
        case totalLocalVideoFilesSize
        case totalVideos
        case totalVideoComments
        case totalLocalVideoChannels
        case totalLocalDailyActiveVideoChannels
        case totalLocalWeeklyActiveVideoChannels
        case totalLocalMonthlyActiveVideoChannels
        case totalLocalPlaylists
        case totalInstanceFollowers
        case totalInstanceFollowing
        case videosRedundancy
        case totalActivityPubMessagesProcessed
        case totalActivityPubMessagesSuccesses
        case totalActivityPubMessagesErrors
        case activityPubMessagesProcessedPerSecond
        case totalActivityPubMessagesWaiting
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(totalUsers, forKey: .totalUsers)
        try container.encodeIfPresent(totalDailyActiveUsers, forKey: .totalDailyActiveUsers)
        try container.encodeIfPresent(totalWeeklyActiveUsers, forKey: .totalWeeklyActiveUsers)
        try container.encodeIfPresent(totalMonthlyActiveUsers, forKey: .totalMonthlyActiveUsers)
        try container.encodeIfPresent(totalLocalVideos, forKey: .totalLocalVideos)
        try container.encodeIfPresent(totalLocalVideoViews, forKey: .totalLocalVideoViews)
        try container.encodeIfPresent(totalLocalVideoComments, forKey: .totalLocalVideoComments)
        try container.encodeIfPresent(totalLocalVideoFilesSize, forKey: .totalLocalVideoFilesSize)
        try container.encodeIfPresent(totalVideos, forKey: .totalVideos)
        try container.encodeIfPresent(totalVideoComments, forKey: .totalVideoComments)
        try container.encodeIfPresent(totalLocalVideoChannels, forKey: .totalLocalVideoChannels)
        try container.encodeIfPresent(totalLocalDailyActiveVideoChannels, forKey: .totalLocalDailyActiveVideoChannels)
        try container.encodeIfPresent(totalLocalWeeklyActiveVideoChannels, forKey: .totalLocalWeeklyActiveVideoChannels)
        try container.encodeIfPresent(totalLocalMonthlyActiveVideoChannels, forKey: .totalLocalMonthlyActiveVideoChannels)
        try container.encodeIfPresent(totalLocalPlaylists, forKey: .totalLocalPlaylists)
        try container.encodeIfPresent(totalInstanceFollowers, forKey: .totalInstanceFollowers)
        try container.encodeIfPresent(totalInstanceFollowing, forKey: .totalInstanceFollowing)
        try container.encodeIfPresent(videosRedundancy, forKey: .videosRedundancy)
        try container.encodeIfPresent(totalActivityPubMessagesProcessed, forKey: .totalActivityPubMessagesProcessed)
        try container.encodeIfPresent(totalActivityPubMessagesSuccesses, forKey: .totalActivityPubMessagesSuccesses)
        try container.encodeIfPresent(totalActivityPubMessagesErrors, forKey: .totalActivityPubMessagesErrors)
        try container.encodeIfPresent(activityPubMessagesProcessedPerSecond, forKey: .activityPubMessagesProcessedPerSecond)
        try container.encodeIfPresent(totalActivityPubMessagesWaiting, forKey: .totalActivityPubMessagesWaiting)
    }
}

