//
// ServerConfigFollowingsInstance.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServerConfigFollowingsInstance: Codable, JSONEncodable, Hashable {

    public var autoFollowIndex: ServerConfigFollowingsInstanceAutoFollowIndex?

    public init(autoFollowIndex: ServerConfigFollowingsInstanceAutoFollowIndex? = nil) {
        self.autoFollowIndex = autoFollowIndex
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case autoFollowIndex
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(autoFollowIndex, forKey: .autoFollowIndex)
    }
}

