//
// UserViewingVideo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserViewingVideo: Codable, JSONEncodable, Hashable {

    public enum ViewEvent: String, Codable, CaseIterable {
        case seek = "seek"
    }
    /** timestamp within the video, in seconds */
    public var currentTime: Int
    /** Event since last viewing call:  * `seek` - If the user seeked the video  */
    public var viewEvent: ViewEvent?

    public init(currentTime: Int, viewEvent: ViewEvent? = nil) {
        self.currentTime = currentTime
        self.viewEvent = viewEvent
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case currentTime
        case viewEvent
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(currentTime, forKey: .currentTime)
        try container.encodeIfPresent(viewEvent, forKey: .viewEvent)
    }
}

