//
// VerifyRegistrationEmailRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct VerifyRegistrationEmailRequest: Codable, JSONEncodable, Hashable {

    public var verificationString: String

    public init(verificationString: String) {
        self.verificationString = verificationString
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case verificationString
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(verificationString, forKey: .verificationString)
    }
}

