//
// VideoRedundancyRedundancies.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct VideoRedundancyRedundancies: Codable, JSONEncodable, Hashable {

    public var files: [FileRedundancyInformation]?
    public var streamingPlaylists: [FileRedundancyInformation]?

    public init(files: [FileRedundancyInformation]? = nil, streamingPlaylists: [FileRedundancyInformation]? = nil) {
        self.files = files
        self.streamingPlaylists = streamingPlaylists
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case files
        case streamingPlaylists
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(files, forKey: .files)
        try container.encodeIfPresent(streamingPlaylists, forKey: .streamingPlaylists)
    }
}

