//
// VideoChannelAllOfOwnerAccount.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct VideoChannelAllOfOwnerAccount: Codable, JSONEncodable, Hashable {

    static let uuidRule = StringRule(minLength: 36, maxLength: 36, pattern: "/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/")
    public var id: Int?
    public var uuid: UUID?

    public init(id: Int? = nil, uuid: UUID? = nil) {
        self.id = id
        self.uuid = uuid
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case uuid
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(uuid, forKey: .uuid)
    }
}

