//
// VideoUploadResponseVideo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct VideoUploadResponseVideo: Codable, JSONEncodable, Hashable {

    static let idRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var id: Int?
    public var uuid: Uuid?
    /** translation of a uuid v4 with a bigger alphabet to have a shorter uuid */
    public var shortUUID: String?

    public init(id: Int? = nil, uuid: Uuid? = nil, shortUUID: String? = nil) {
        self.id = id
        self.uuid = uuid
        self.shortUUID = shortUUID
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case uuid
        case shortUUID
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(uuid, forKey: .uuid)
        try container.encodeIfPresent(shortUUID, forKey: .shortUUID)
    }
}

