//
// RunnersAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class RunnersAPI {

    /**
     * enum for parameter sort
     */
    public enum Sort_apiV1RunnersGet: String, CaseIterable {
        case createdat = "createdAt"
    }

    /**
     List runners
     
     - parameter start: (query) Offset used to paginate results (optional)
     - parameter count: (query) Number of items to return (optional, default to 15)
     - parameter sort: (query) Sort runners by criteria (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func apiV1RunnersGet(start: Int? = nil, count: Int? = nil, sort: Sort_apiV1RunnersGet? = nil, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: ApiV1RunnersGet200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return apiV1RunnersGetWithRequestBuilder(start: start, count: count, sort: sort).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List runners
     - GET /api/v1/runners
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter start: (query) Offset used to paginate results (optional)
     - parameter count: (query) Number of items to return (optional, default to 15)
     - parameter sort: (query) Sort runners by criteria (optional)
     - returns: RequestBuilder<ApiV1RunnersGet200Response> 
     */
    open class func apiV1RunnersGetWithRequestBuilder(start: Int? = nil, count: Int? = nil, sort: Sort_apiV1RunnersGet? = nil) -> RequestBuilder<ApiV1RunnersGet200Response> {
        let localVariablePath = "/api/v1/runners"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "start": (wrappedValue: start?.encodeToJSON(), isExplode: true),
            "count": (wrappedValue: count?.encodeToJSON(), isExplode: true),
            "sort": (wrappedValue: sort?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ApiV1RunnersGet200Response>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Register a new runner
     
     - parameter apiV1RunnersRegisterPostRequest: (body)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func apiV1RunnersRegisterPost(apiV1RunnersRegisterPostRequest: ApiV1RunnersRegisterPostRequest? = nil, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: ApiV1RunnersRegisterPost200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return apiV1RunnersRegisterPostWithRequestBuilder(apiV1RunnersRegisterPostRequest: apiV1RunnersRegisterPostRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Register a new runner
     - POST /api/v1/runners/register
     - API used by PeerTube runners
     - parameter apiV1RunnersRegisterPostRequest: (body)  (optional)
     - returns: RequestBuilder<ApiV1RunnersRegisterPost200Response> 
     */
    open class func apiV1RunnersRegisterPostWithRequestBuilder(apiV1RunnersRegisterPostRequest: ApiV1RunnersRegisterPostRequest? = nil) -> RequestBuilder<ApiV1RunnersRegisterPost200Response> {
        let localVariablePath = "/api/v1/runners/register"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: apiV1RunnersRegisterPostRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ApiV1RunnersRegisterPost200Response>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Delete a runner
     
     - parameter runnerId: (path)  
     - parameter apiV1RunnersUnregisterPostRequest: (body)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func apiV1RunnersRunnerIdDelete(runnerId: Int, apiV1RunnersUnregisterPostRequest: ApiV1RunnersUnregisterPostRequest? = nil, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) -> RequestTask {
        return apiV1RunnersRunnerIdDeleteWithRequestBuilder(runnerId: runnerId, apiV1RunnersUnregisterPostRequest: apiV1RunnersUnregisterPostRequest).execute(apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Delete a runner
     - DELETE /api/v1/runners/{runnerId}
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter runnerId: (path)  
     - parameter apiV1RunnersUnregisterPostRequest: (body)  (optional)
     - returns: RequestBuilder<Void> 
     */
    open class func apiV1RunnersRunnerIdDeleteWithRequestBuilder(runnerId: Int, apiV1RunnersUnregisterPostRequest: ApiV1RunnersUnregisterPostRequest? = nil) -> RequestBuilder<Void> {
        var localVariablePath = "/api/v1/runners/{runnerId}"
        let runnerIdPreEscape = "\(APIHelper.mapValueToPathItem(runnerId))"
        let runnerIdPostEscape = runnerIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{runnerId}", with: runnerIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: apiV1RunnersUnregisterPostRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = OpenAPIClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Unregister a runner
     
     - parameter apiV1RunnersUnregisterPostRequest: (body)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func apiV1RunnersUnregisterPost(apiV1RunnersUnregisterPostRequest: ApiV1RunnersUnregisterPostRequest? = nil, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) -> RequestTask {
        return apiV1RunnersUnregisterPostWithRequestBuilder(apiV1RunnersUnregisterPostRequest: apiV1RunnersUnregisterPostRequest).execute(apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Unregister a runner
     - POST /api/v1/runners/unregister
     - API used by PeerTube runners
     - parameter apiV1RunnersUnregisterPostRequest: (body)  (optional)
     - returns: RequestBuilder<Void> 
     */
    open class func apiV1RunnersUnregisterPostWithRequestBuilder(apiV1RunnersUnregisterPostRequest: ApiV1RunnersUnregisterPostRequest? = nil) -> RequestBuilder<Void> {
        let localVariablePath = "/api/v1/runners/unregister"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: apiV1RunnersUnregisterPostRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = OpenAPIClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
